name: check

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Validate package.json
        run: |
          node -e "JSON.parse(require('fs').readFileSync('package.json','utf8'))"

      - name: Install Dependencies
        run: npm install

      - name: Audit Dependencies
        run: npm audit
        continue-on-error: true

      - name: Test Project
        run: npx jest

      - name: Check linting
        run: npx eslint --report-unused-disable-directives .
        continue-on-error: true

      - name: Build Project
        run: npx lichtblick-extension build
